### ISSUE TITLE
Name collision with `tex` typesetting system (that is, with "TeX").

### ISSUE THREAD

**Issue by kfogel** [doawoo/tex#1]
Hi, @doawoo.  Were you aware of the name collision with the widely-distributed `tex` typesetting system?  (Among other things, it's what LaTeX and other things are based on.)  It's `/usr/bin/tex` on my system, and that will be true for a lot of other people as well, since TeX is quite widely used and often comes installed by default with an operating system.

Best regards,
-Karl

**Comment by sthornington** [comment]
Seconded

**Comment by doawoo** [comment]
Hey there!
Thanks for the report. I'd be happy to rename the cli tool if it's causes collisions on the cli.
perhaps something like `tex-tool` or `texutil` to avoid path collisions!

possibly even just `elixir-tex`

**Comment by kfogel** [comment]
You're welcome!  I don't have a brilliant idea for the name, but watch out for `tex` even as a component.  The TeX typesetting system has been at large for decades, and has grown a lot of helper tools etc, and they tend to all have "tex" in their names, to the point where when people see that substring they simply assume that the command has something to do with TeX.  (My system has 187 commands with "tex" as a substring, for example, and I'm by no means a TeX specialist though I do use it.)

**Comment by doawoo** [comment]
I'll be renaming the project to "Teex" (following the "ee" lots of elixir libs use in their name) shortly. I shall deprecate the Hex package called "tex" and redirect everything to the new package!

**Comment by kfogel** [comment]
Ah, good solution!  Thanks, @doawoo.
